# Generated by Django 3.0.2 on 2020-01-04 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("accounts", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Token",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("uid", models.CharField(max_length=40)),
            ],
        ),
        migrations.RemoveField(model_name="user", name="id"),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
