# Generated by Django 2.2.7 on 2019-11-29 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("lists", "0003_list")]

    operations = [
        migrations.AddField(
            model_name="item",
            name="list",
            field=models.ForeignKey(default=None, on_delete="PROTECT", to="lists.List"),
        )
    ]
