# Generated by Django 2.2.8 on 2019-12-29 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("lists", "0004_item_list")]

    operations = [
        migrations.AlterModelOptions(name="item", options={"ordering": ("id",)}),
        migrations.AlterUniqueTogether(name="item", unique_together={("list", "text")}),
    ]
