# Generated by Django 3.0.2 on 2020-01-21 16:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("lists", "0006_list_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="list",
            name="shared_with",
            field=models.ManyToManyField(
                blank=True, related_name="shared_with", to=settings.AUTH_USER_MODEL
            ),
        )
    ]
